tap "aws/tap"
brew "awscli"
brew "blueutil"
brew "curl"
brew "gh"
brew "git"
brew "git-delta"
brew "jq"
brew "lazygit"
brew "mise"
brew "neovim"
brew "peco"
brew "sheldon"
brew "starship"

cask "aldente" # https://github.com/davidwernhart/AlDente
cask "beekeeper-studio"
cask "coteditor"
cask "docker"
cask "google-cloud-sdk"
cask "google-japanese-ime"
cask "ghostty"
cask "kap" # https://getkap.co/
cask "karabiner-elements"
cask "keycastr"
cask "raycast"
cask "skitch"
cask "visual-studio-code"
